# -*- coding: utf-8 -*-
{
    "name": "Educational Management",
    "version": "18.0.1.0.0",
    "category": "Education",
    "summary": "Manage educational entities and processes",
    "author": "",
    "website": "",
    "license": "LGPL-3",
    "depends": ["base", "account", "product"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/dashboard_data.xml",
        "reports/report_views.xml",
        "reports/report_templates.xml",
        "views/academic_views.xml",
        "views/people_views.xml",
        "views/learning_views.xml",
        "views/attendance_views.xml",
        "views/exam_views.xml",
        "views/fee_views.xml",
        "views/operations_views.xml",
        "views/dashboard_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "installable": True,
}
